#!/usr/bin/env python3
"""Merge intent_data.jsonl (consolidated), dedupe, stratified 85/15 split.

Produces:
  MLTraining/intent_training.json
  MLTraining/intent_validation.json
"""
import json
import random
import sys
from pathlib import Path
from collections import Counter

SEED = 42
SPLIT_RATIO = 0.85
VALID_LABELS = {"tool_action", "knowledge", "conversation", "refinement", "meta"}
# Phase-2.5-v2: with ~2000+ examples per class from the 4-5x expansion,
# capping is less critical. Set generous ceilings to preserve balance
# without discarding useful diversity. The `tool_action` cap stays lowest
# because mined data continues to carry noise (see `intent_audit.jsonl`).
PER_CLASS_CAP = {
    "tool_action": 2500,
    "knowledge": 2500,
    "conversation": 2500,
    "refinement": 2500,
    "meta": 2500,
}

root = Path(__file__).resolve().parent
# Single consolidated source file. Generated by concatenating the prior
# per-iteration files (intent_data_a..j.jsonl) — see git history for the
# rationale. Adding new examples = append to this file.
inputs = [root / "intent_data.jsonl"]

# Apply the audit filter when present. Entries in `intent_audit.jsonl`
# with issue ∈ {low_quality, generator_artifact, ambiguous} are dropped;
# entries with `wrong_label`/`duplicate_conflict` are relabeled.
audit_path = root / "intent_audit.jsonl"
out_train = root / "intent_training.json"
out_val = root / "intent_validation.json"


def load_jsonl(path):
    records = []
    if not path.exists():
        print(f"WARN: {path} missing", file=sys.stderr)
        return records
    with path.open() as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError as e:
                print(f"  {path.name}:{line_num} bad JSON: {e}", file=sys.stderr)
                continue
            text = rec.get("text")
            label = rec.get("label")
            if not isinstance(text, str) or not isinstance(label, str):
                continue
            text = text.strip()
            if not text or len(text) < 2:
                continue
            if label not in VALID_LABELS:
                print(f"  {path.name}:{line_num} invalid label {label!r}", file=sys.stderr)
                continue
            records.append({"text": text, "label": label})
    return records


def load_audit(path):
    """Returns dict: text.lower() -> {action: 'drop'|'relabel', new_label?}."""
    actions: dict = {}
    if not path.exists():
        return actions
    drop_issues = {"low_quality", "generator_artifact", "ambiguous"}
    relabel_issues = {"wrong_label", "duplicate_conflict"}
    count_drop = count_relabel = 0
    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            text = rec.get("text", "").strip().lower()
            issue = rec.get("issue", "")
            if not text:
                continue
            if issue in drop_issues:
                actions[text] = {"action": "drop"}
                count_drop += 1
            elif issue in relabel_issues and rec.get("suggested_label"):
                actions[text] = {
                    "action": "relabel",
                    "new_label": rec["suggested_label"],
                }
                count_relabel += 1
    print(f"Audit loaded: drop={count_drop} relabel={count_relabel}")
    return actions


def main():
    audit = load_audit(audit_path)
    all_records = []
    for p in inputs:
        before = len(all_records)
        loaded = load_jsonl(p)
        # Apply audit decisions per record.
        filtered = []
        for r in loaded:
            key = r["text"].strip().lower()
            if key in audit:
                a = audit[key]
                if a["action"] == "drop":
                    continue
                if a["action"] == "relabel" and a["new_label"] in VALID_LABELS:
                    filtered.append({"text": r["text"], "label": a["new_label"]})
                    continue
            filtered.append(r)
        all_records.extend(filtered)
        print(f"Loaded {len(all_records) - before} from {p.name} (raw {len(loaded)})")

    seen = set()
    unique = []
    for r in all_records:
        key = (r["text"].lower(), r["label"])
        if key in seen:
            continue
        seen.add(key)
        unique.append(r)
    print(f"After dedupe: {len(unique)} (removed {len(all_records) - len(unique)})")

    # Apply per-class caps to prevent any single label from dominating.
    random.seed(SEED)
    if PER_CLASS_CAP:
        by_label_tmp: dict = {}
        for r in unique:
            by_label_tmp.setdefault(r["label"], []).append(r)
        capped = []
        for label, recs in by_label_tmp.items():
            cap = PER_CLASS_CAP.get(label)
            if cap is not None and len(recs) > cap:
                random.shuffle(recs)
                kept = recs[:cap]
                print(f"  Capped {label}: {len(recs)} -> {cap}")
                capped.extend(kept)
            else:
                capped.extend(recs)
        unique = capped
        print(f"After capping: {len(unique)}")

    counts = Counter(r["label"] for r in unique)
    print("Label distribution:")
    for label, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        print(f"  {label:<18} {n:>5}")

    random.seed(SEED)
    by_label = {}
    for r in unique:
        by_label.setdefault(r["label"], []).append(r)
    train = []
    val = []
    for label, recs in by_label.items():
        random.shuffle(recs)
        cut = int(len(recs) * SPLIT_RATIO)
        train.extend(recs[:cut])
        val.extend(recs[cut:])

    random.shuffle(train)
    random.shuffle(val)

    out_train.write_text(json.dumps(train, ensure_ascii=False))
    out_val.write_text(json.dumps(val, ensure_ascii=False))
    print(f"Wrote {len(train)} train -> {out_train.name}")
    print(f"Wrote {len(val)} val   -> {out_val.name}")


if __name__ == "__main__":
    main()
