import Foundation
import FoundationModels

/// A single step in an agent execution plan, produced by structured LLM generation.
///
/// Replaces the fragile `"ToolName: input text"` string parsing in the old
/// `ExecutionPlanner.parseSteps()` with type-safe structured output via `@Generable`.
/// Foundation Models guarantees structural validity — no more formatting failures.
@Generable
public struct PlanStep: ConvertibleFromGeneratedContent, Sendable, Codable {
    @Guide(description: "The name of the tool to invoke (must match a registered tool name)")
    public var toolName: String

    @Guide(description: "Natural language input for this tool. Describe what data to get or action to take.")
    public var input: String

    @Guide(description: "If true, this step needs the output of the previous step. The agent will substitute the prior result into the input.")
    public var dependsOnPrevious: Bool
}

/// A structured execution plan generated by the LLM via `@Generable`.
///
/// This replaces the old `ExecutionPlan` struct + `ExecutionPlanner` actor's
/// string-based decomposition. The LLM produces a valid `AgentPlan` directly
/// through guided generation — no regex parsing, no `"ToolName: input"` format.
@Generable
public struct AgentPlan: ConvertibleFromGeneratedContent, Sendable, Codable {
    @Guide(description: "Ordered steps to complete the task. Use 1 step for simple requests, up to 3 for complex ones.")
    public var steps: [PlanStep]
}

extension PlanStep: JSONSchemaProviding {
    public static var jsonSchema: [String: Any] {
        [
            "type": "object",
            "properties": [
                "toolName": ["type": "string", "description": "name of the tool to invoke"],
                "input": ["type": "string", "description": "natural language input for this tool"],
                "dependsOnPrevious": ["type": "boolean", "description": "true if this step needs the output of the previous step"]
            ],
            "required": ["toolName", "input", "dependsOnPrevious"]
        ]
    }
}

extension AgentPlan: JSONSchemaProviding {
    public static var jsonSchema: [String: Any] {
        [
            "type": "object",
            "properties": [
                "steps": [
                    "type": "array",
                    "items": PlanStep.jsonSchema,
                    "description": "ordered steps to complete the task (1-3)"
                ] as [String: Any]
            ],
            "required": ["steps"]
        ]
    }
}

// MARK: - Plan Execution Helpers

extension AgentPlan {
    /// Whether this plan requires multiple tool invocations.
    public var isMultiStep: Bool { steps.count > 1 }

    /// Resolves step inputs by substituting prior results where `dependsOnPrevious` is true.
    public func resolvedInput(for stepIndex: Int, priorResult: String?) -> String {
        let step = steps[stepIndex]
        guard step.dependsOnPrevious, let prior = priorResult else {
            return step.input
        }
        // If the input references the prior result, append it as context.
        // The LLM already knows this step depends on the previous one,
        // so we provide the data directly.
        return "\(step.input) [Prior result: \(prior)]"
    }

    /// Validates tool names against the registry. Returns steps with invalid tools removed.
    /// Uses fuzzy matching: exact → case-insensitive → contains (e.g., "GoogleSearch" → "WebSearch"
    /// won't match, but "websearch" → "web_search" will via underscore-stripped comparison).
    public func validated(knownTools: Set<String>) -> AgentPlan {
        let validSteps = steps.compactMap { step -> PlanStep? in
            guard let validName = Self.fuzzyMatch(step.toolName, in: knownTools) else {
                Log.engine.debug("AgentPlan: removing step with unknown tool '\(step.toolName)'")
                return nil
            }
            var corrected = step
            corrected.toolName = validName
            return corrected
        }
        return AgentPlan(steps: validSteps)
    }

    /// Fuzzy-matches a tool name against known tools.
    /// Priority: exact → case-insensitive → normalized (strip underscores/spaces).
    private static func fuzzyMatch(_ name: String, in known: Set<String>) -> String? {
        // 1. Exact match
        if known.contains(name) { return name }
        // 2. Case-insensitive
        if let match = known.first(where: { $0.caseInsensitiveCompare(name) == .orderedSame }) {
            return match
        }
        // 3. Normalized: strip underscores and spaces, then case-insensitive
        let normalized = name.replacingOccurrences(of: "_", with: "").replacingOccurrences(of: " ", with: "").lowercased()
        if let match = known.first(where: {
            $0.replacingOccurrences(of: "_", with: "").replacingOccurrences(of: " ", with: "").lowercased() == normalized
        }) {
            Log.engine.debug("AgentPlan: fuzzy-matched '\(name)' → '\(match)'")
            return match
        }
        return nil
    }
}

// MARK: - Plan Generation

/// Generates an `AgentPlan` from a user query using structured LLM output.
///
/// This replaces `ExecutionPlanner` entirely. Instead of heuristic detection
/// (`needsPlanning()` with hardcoded English phrases) + string-parsed LLM output,
/// it always asks the LLM and gets a guaranteed-valid struct back.
public actor AgentPlanner {

    /// Test injection: returns a pre-built plan without calling the LLM.
    public typealias PlannerOverride = @Sendable (String, Set<String>) async throws -> AgentPlan

    private let plannerOverride: PlannerOverride?
    private let llmAdapter: LLMAdapter

    public init(plannerOverride: PlannerOverride? = nil, llmAdapter: LLMAdapter = .shared) {
        self.plannerOverride = plannerOverride
        self.llmAdapter = llmAdapter
    }

    /// Generates a plan for the given input.
    ///
    /// Uses `@Generable` structured output to decompose the query into tool steps.
    /// The LLM decides whether 1 or multiple steps are needed — no hardcoded
    /// English heuristics like "then", "and then", "where my".
    ///
    /// - Parameters:
    ///   - input: The user's natural language query.
    ///   - availableTools: Tool names the plan can reference.
    ///   - routedTool: The tool already identified by the ML classifier (used as hint).
    /// - Returns: A validated `AgentPlan`.
    public func plan(
        input: String,
        availableTools: Set<String>,
        routedTool: String? = nil
    ) async -> AgentPlan {
        // Test override
        if let override = plannerOverride {
            do {
                return try await override(input, availableTools)
            } catch {
                Log.engine.debug("Planner override failed: \(error)")
            }
        }

        let toolList = availableTools.sorted().joined(separator: ", ")
        let hint = routedTool.map { " The most likely primary tool is '\($0)'." } ?? ""

        let instructions = makeInstructions {
            Directive("""
            You are a task planner. Decompose the user's request into 1-3 tool steps.
            Available tools: \(toolList).\(hint)
            Most requests need only 1 step. Use multiple steps only when one tool's output \
            is required as input to another, or when the user wants multiple independent results.
            """)
        }

        do {
            try Task.checkCancellation()
            let plan = try await llmAdapter.generateStructured(
                prompt: input,
                instructions: instructions,
                generating: AgentPlan.self,
                profile: .planning
            )
            try Task.checkCancellation()
            let validated = plan.validated(knownTools: availableTools)
            guard !validated.steps.isEmpty else {
                return singleStepFallback(tool: routedTool ?? availableTools.first ?? ToolNames.help, input: input)
            }
            return validated
        } catch {
            Log.engine.debug("AgentPlanner LLM failed: \(error). Falling back to single step.")
            return singleStepFallback(tool: routedTool ?? ToolNames.help, input: input)
        }
    }

    /// Creates a trivial single-step plan as fallback.
    private func singleStepFallback(tool: String, input: String) -> AgentPlan {
        AgentPlan(steps: [PlanStep(toolName: tool, input: input, dependsOnPrevious: false)])
    }
}
